name: PronounChoice
version: '${version}'
main: xyz.chaoscorner.pronounchoice.PronounChoice
api-version: 1.18
depend:
  - LuckPerms
commands:
  pronoun:
    description: Manage pronouns for you or another user
    usage: /<command> <addgroup|removegroup|set|remove|list|current|version>
    aliases: pn
permissions:
  pronoun.user:
    default: true
    description: All the main commands
    children:
      pronoun.set.self: true
      pronoun.remove.self: true
      pronoun.help: true
      pronoun.list: true
      pronoun.current.self: true
      pronoun.current.others: true
  pronoun.admin:
    default: op
    description: All admin commands which manage pronouns
    children:
      pronoun.addgroup: true
      pronoun.removegroup: true
      pronoun.set.others: true
      pronoun.remove.others: true
  pronoun.addgroup:
    description: Adds a pronoun group into LuckPerms
  pronoun.removegroup:
    description: Deletes a pronoun group in LuckPerms
  pronoun.set.self:
    description: Sets your pronouns
  pronoun.set.others:
    description: Sets another user's pronouns
  pronoun.remove.self:
    description: Removes your pronouns
  pronoun.remove.others:
    description: Removes another user's pronouns
  pronoun.list:
    description: Lists all available pronouns
  pronoun.current.self:
    description: Shows your current pronouns
  pronoun.current.others:
    description: Shows another user's current pronouns
  pronoun.help:
    description: Shows the current version and usage of the plugin

